"""Add interview_preps table

Revision ID: 8aab206855b2
Revises: 3a2d46cb5c91
Create Date: 2026-08-11 11:19:07.615840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8aab206855b2'
down_revision: Union[str, None] = '3a2d46cb5c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_preps',
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('company_dossier', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('technical_drills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('behavioral_drills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pitch_ideas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.drop_table('interview_preps')
    # ### end Alembic commands ###
